---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/homarr-labs/homarr
      tag: latest
      pullPolicy: Always
    ingress:
      main:
        enabled: true
        hosts:
          - host: "homarr.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
    service:
      main:
        controller: deployment
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        existingClaim: homarr-config
    env:
      TZ: America/Toronto
