---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  interval: 20m
  upgrade:
    force: true
  chart:
    spec:
      chart: minecraft
      version: 4.26.4
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 20m
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-config
        mountPath: /data
    minecraftServer:
      eula: 'TRUE'
      type: 'AUTO_CURSEFORGE'
      autoCurseForge:
        apiKey:
          key: "${cf_api_key}"
          existingSecret: ""
          secretKey: cf-api-key
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/farming-crossing-5-made-to-order"
        slug: "farming-crossing-5-made-to-order"
      whitelist: 'tty_, angelbbyabby'
      ops: 'tty_, angelbbyabby'
      maxPlayers: 2
      motd: "modded"
      difficulty: 'easy'
      serviceType: LoadBalancer
      loadBalancerIP: "${minecraft_ip}"
      levelSeed: '-2032795982907864146'
