---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart:
        spec:
          chart: minecraft
          version: 4.26.0
          sourceRef:
            kind: HelmRepository
            name: minecraft-server-charts
            namespace: flux-system
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest
      pullPolicy: Always
    ingress:
      main:
        enabled: true
        hosts:
          - host: "minecraft.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        ports:
          http:
            port: 25565
            protocol: TCP
    persistence:
      data:
        enabled: true
        existingClaim: minecraft-config
    podSecurityContext:
      fsGroup: 568
    minecraftServer:
      eula: 'TRUE'
      type: 'VANILLA'
      version: 'LATEST'
      whitelist: 'tty_, abbybabyyy'
      maxPlayers: 2
      difficulty: 'easy'
