---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: minecraft
      version: 4.26.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest
      pullPolicy: Always
    service:
      main:
        controller: main
        type: LoadBalancer
        loadBalancerIP: ${minecraft_ip}
        ports:
          mqtt:
            enabled: true
            primary: true
            port: 25565
    persistence:
      data:
        enabled: true
        existingClaim: minecraft-config
    minecraftServer:
      eula: 'TRUE'
      type: 'VANILLA'
      version: 'LATEST'
      whitelist: 'tty_, abbybabyyy'
      maxPlayers: 2
      difficulty: 'easy'
