---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  interval: 20m
  upgrade:
    force: true
    timeout: 20m
  chart:
    spec:
      chart: minecraft
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 20m
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-config
        mountPath: /data
    minecraftServer:
      eula: 'TRUE'
      type: 'FABRIC'
      modrinth:
        projects:
          - 'fabric-api'
          - 'lithium'
        downloadDependencies: "optional"
      whitelist: 'tty_, angelbbyabby'
      ops: 'tty_, angelbbyabby'
      maxPlayers: 2
      motd: "new world"
      difficulty: 'easy'
      serviceType: LoadBalancer
      loadBalancerIP: "${minecraft_ip}"
      levelSeed: '-2032795982907864146'
