---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  interval: 20m
  upgrade:
    force: true
    timeout: 20m
  chart:
    spec:
      chart: minecraft
      version: 4.26.4
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 20m
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-config
        mountPath: /data
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 3000
    resources:
      requests:
        cpu: "1000m"
        memory: "4Gi"
      limits:
        cpu: "2000m"
        memory: "8Gi"
    livenessProbe:
      initialDelaySeconds: 600 
      periodSeconds: 60
      failureThreshold: 10
    readinessProbe:
      initialDelaySeconds: 600
      periodSeconds: 60
      failureThreshold: 10
    minecraftServer:
      eula: 'TRUE'
      type: 'AUTO_CURSEFORGE'
      forceReDownload: true
      autoCurseForge:
        apiKey:
          key: "${cf_api_key}"
          secretKey: cf-api-key
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/farming-crossing-5-made-to-order"
        slug: "farming-crossing-5-made-to-order"
        setLevelFrom: "WORLD_FILE"
        forceUpdate: true
      whitelist: 'tty_, angelbbyabby'
      ops: 'tty_, angelbbyabby'
      maxPlayers: 2
      motd: "modded"
      difficulty: 'easy'
      serviceType: LoadBalancer
      loadBalancerIP: "${minecraft_ip}"
      levelSeed: '-2032795982907864146'
