---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: old-minecraft
  namespace: games
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: minecraft
      version: 4.26.1
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest
    persistence:
      dataDir:
        enabled: true
        existingClaim: old-minecraft-config
        mountPath: /data
    minecraftServer:
      eula: 'TRUE'
      type: 'VANILLA'
      version: 'LATEST'
      whitelist: 'tty_, angelbbyabby'
      ops: 'tty_, angelbbyabby'
      maxPlayers: 2
      motd: "old world"
      difficulty: 'easy'
      serviceType: LoadBalancer
      servicePort: 25566
      loadBalancerIP: "${old_minecraft_ip}"
