apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager-webhook-duckdns
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 5m
