---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: site
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: maneeshwije/personal-website
      tag: latest
      pullPolicy: Always

    service:
      main:
        ports:
          http:
            port: 8080
    
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: site.local
            paths:
              - path: /
                pathType: Prefix
