---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: site
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: maneeshwije/personal-website
      tag: "sha256:c889172a13b49083f1830d079ce69a32c0bc9666cd961e70b203dedc815b3e09"
      pullPolicy: Always
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        hosts:
          - host: "${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 80
