---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: 0.6.9-ollama
              pullPolicy: Always
            env:
              DATABASE_URL: sqlite:////app/backend/data/webui_db/webui.db
              OLLAMA_HOST: 0.0.0.0:11434
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        hosts:
          - host: "ollama.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
      api:
        controller: main
        ports:
          http:
            port: 11434

    persistence:
      models:
        enabled: true
        type: hostPath
        hostPath: /ollama/models
        advancedMounts:
          main:
            main:
              - path: /root/.ollama/models

      data:
        enabled: true
        existingClaim: ollama-data
        advancedMounts:
          main:
            main:
              - path: /app/backend/data/webui_db
                subPath: webui_db
                readOnly: false
              - path: /app/backend/data/vector_db
                subPath: vector_db
                readOnly: false
              - path: /app/backend/data/uploads
                subPath: uploads
                readOnly: false
