---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 10m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
      interval: 10m
  values:
    controllers:
      main:
        initContainers:
          copy-natpmpc:
            image:
              repository: alpine
              tag: latest
            command:
              - /bin/sh
              - -c
            args:
              - |
                apk add --no-cache natpmp && \
                cp /usr/bin/natpmpc /shared/natpmpc
        containers:
          main:
            image:
              repository: haugene/transmission-openvpn
              tag: dev
            securityContext:
              fsGroup: 0
              runAsUser: 0
              runAsGroup: 0
              fsGroupChangePolicy: "Always"
              capabilities:
                add:
                  - NET_ADMIN
            env:
              TZ: America/Toronto
              OPENVPN_USERNAME: "${vpn_proton_username}"
              OPENVPN_PASSWORD: "${vpn_proton_password}"
              OPENVPN_PROVIDER: CUSTOM
              OPENVPN_CONFIG: nl.protonvpn.udp
              LOCAL_NETWORK: "10.42.0.0/16,10.43.0.0/16,192.168.0.0/24"
              PUID: 0
              PGID: 0
              TRANSMISSION_DOWNLOAD_DIR: /downloads
              TRANSMISSION_INCOMPLETE_DIR_ENABLED: false
        pod:
          securityContext:
            fsGroup: 0
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "transmission.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 9091
    persistence:
      config:
        enabled: true
        existingClaim: transmission-config
        globalMounts:
          - path: /config
            readOnly: false
      vpn-config:
        enabled: true
        existingClaim: transmission-ovpn-config
        globalMounts:
          - path: /etc/openvpn/custom/
            readOnly: false
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /media/Downloads
        globalMounts:
          - path: /downloads
            readOnly: false
      natpmpc-bin:
        type: emptyDir
        globalMounts:
          - path: /shared
            readOnly: false
          - path: /usr/local/bin/natpmpc
            subPath: natpmpc
            readOnly: true
