---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: admin
data:
  dynamic.yml: |
    http:
      middlewares:
        basic:
          basicAuth:
            users: [""]
        localOnly:
          ipWhiteList:
            sourceRange:
              - "${network_subnet}"
        redirect-to-non-www:
          redirectRegex:
            regex: "^https?://([a-zA-Z0-9-]+)\\.(${domain})"
            replacement: "https://$2"
            permanent: true

      routers:
        api:
          rule: "Host(`traefik.${domain}`)"
          entrypoints: ["websecure"]
          service: "api@internal"
          middlewares:
            - "localOnly@file"
        
        redirect-www-to-non-www:
          rule: "HostRegexp(`{subdomain:.+}.${domain}`)"
          entrypoints: ["web", "websecure", "web-ext", "websecure-ext"]
          middlewares:
            - "redirect-to-non-www@file"
          service: "noop-service"

      services:
        noop-service:
          loadBalancer:
            servers:
              - url: "http://127.0.0.1"  # Placeholder server for redirection
