---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: admin
data:
  dynamic.yml: |
    http:
      middlewares:
        # Middleware to redirect www to non-www
        redirectWWWToNonWWW:
          redirectRegex:
            regex: "^https?://www\.(.*)"
            replacement: "https://$1"
            permanent: true
        basic:
          basicAuth:
            users: [""]
        localOnly:
          ipWhiteList:
            sourceRange:
              - "${network_subnet}"

      routers:
        api:
          rule: "Host(`traefik.${domain}`)"
          entrypoints: ["websecure"]
          service: "api@internal"
          middlewares:
            - "localOnly@file"

        default-router:
          rule: "HostRegexp(`www.{subdomain:.+}.{domain}`) || Host(`www.{domain}`)"
          entrypoints: ["web", "websecure"]
          middlewares:
            - "redirectWWWToNonWWW@file"
          service: "default-service"
