---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: admin
data:
  dynamic.yml: |
    http:
      middlewares:
        basic:
          basicAuth:
            users: [""]
        localOnly:
          ipAllowList:
            sourceRange:
              - "${network_subnet}"
        sslHeaderMiddleware:
          headers:
            customRequestHeaders:
              X-Forwarded-Proto: "https"
      routers:
        api:
          rule: "Host(`traefik.${domain}`)"
          entrypoints: ["websecure"]
          service: "api@internal"
          middlewares:
            - "localOnly@file"
            - "sslHeaderMiddleware@file"
