apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: admin
data:
  dynamic.yml: |
    http:
      middlewares:
        basic:
          basicAuth:
            users: [""]
        redirect-www:
          redirectRegex:
            regex: "^https?://www\\.(.*)"
            replacement: "https://$1"
            permanent: true
      entryPoints:
        websecure:
          http:
            middlewares:
              - redirect-www
        websecure-ext:
          http:
            middlewares:
              - redirect-www
      routers:
        api:
          rule: "Host(`traefik.${domain}`)"
          entrypoints: ["websecure"]
          service: "api@internal"
