---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: admin
spec:
  schedule: "*/50 * * * *"  # Runs every 50 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              image: kubitodev/kubernetes-cloudflare-ddns:2.0.0
              env:
                - name: authKey
                  value: "${ddns_cf_token}"
                - name: dnsRecord
                  value: "${domain}"
                - name: recordId
                  value: "${ddns_record_id}"
                - name: zoneId
                  value: "${ddns_zone_id}"
          restartPolicy: Never
