---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: admin
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              image: kubitodev/kubernetes-cloudflare-ddns:1.0.1
              env:
                authKey: "${ddns_cf_token}"
                dnsRecord: "${domain}"
                recordId: "${ddns_record_id}"
                zoneId: "${ddns_zone_id}"
          restartPolicy: Never
