---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookshelf
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/pennydreadful/bookshelf
              tag: hardcover-v0.4.20.91@sha256:00997a32b855bc25c21751747713abd10ddf80655866401a2863711d5efc858a
            securityContext:
              fsGroup: 0
              runAsUser: 0
              runAsGroup: 0
              fsGroupChangePolicy: "Always"
            env:
              TZ: America/Toronto

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "bookshelf.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 8797

    persistence:
      config:
        enabled: true
        existingClaim: bookshelf-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /gargantua/
        globalMounts:
          - path: /gargantua
            readOnly: false
