---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: watch-together
  namespace: projects
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: maneeshwije/watch-together
      tag: latest
      pullPolicy: Always
    
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        hosts:
          - host: "watch.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 8080

    env:
      - name: DATABASE_PUBLIC_URL
        valueFrom:
          secretKeyRef:
            name: watch-together-secrets
            key: DATABASE_PUBLIC_URL
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: watch-together-secrets
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: watch-together-secrets
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_S3_BUCKET
        valueFrom:
          secretKeyRef:
            name: watch-together-secrets
            key: AWS_S3_BUCKET
      - name: GOOGLE_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: watch-together-secrets
            key: GOOGLE_CLIENT_ID
      - name: GOOGLE_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: watch-together-secrets
            key: GOOGLE_CLIENT_SECRET
      - name: GOOGLE_REDIRECT_URL
        valueFrom:
          secretKeyRef:
            name: watch-together-secrets
            key: GOOGLE_REDIRECT_URL
