apiVersion: v1
kind: Secret
metadata:
    name: watch-together-secrets
    namespace: projects
stringData:
    AWS_URL: ENC[AES256_GCM,data:b+k72o3pmzhE+g/4RSW8Te7u0SyE0bs+l182+i4SMQqcSeUkvHZ3vYRiNJWvQ3uHmK/5DrUEbHQ=,iv:hpB7+DpwzrGAnHipPIwjlncK6dqu1cQv84WKoB6wPes=,tag:zSxk0eRRmPQooksZ1g8Xnw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IQUN0Z+E6+rx5iGfw0E+44PoD8o=,iv:/7OdX7C5XDDKSG0NsPf/QmCRcanvCsV5dGnttyNkxQ4=,tag:FM3am6s9xxEcRP6U12Zw5w==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:00decHoF8X/M,iv:mcv9g0j8udEXwW8ciz57R6FA/qPdHRunILZpCyIv9/U=,tag:V2BLklMXsd0Hu9x/EzZsGQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GdlwhWmm6AjlMMv4hLkC+/91y1/cDh5YuCx4rUkETn+UmrFvfjeDqA==,iv:unUCKvvl+I4uFl3GIKG3Q/RvnBJFYuXP2iC0bs00iIY=,tag:LGcx0vRGfUlX5hsEGgAq2g==,type:str]
    AWS_S3_BUCKET: ENC[AES256_GCM,data:6Gvy7vHCz8OiTAbEBO9GDGuTAFQj,iv:SLbrWJA/wVIzYoY45HiO0pn1HZIU2OZhOHMDgPifW54=,tag:nrbonJe6gkTWy64b0lfLeA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:c2HLkmHfDuQRW4gbGLwL5/gVQNtOq/wp8JG9jo8u/hCn615SrIopwVXibZvGb+5M2DV8IZqBxM3skIf0g+botk28VFb93nXroLeNDjU2AtFxSua4xOS/8uEqDQirnTH+IhwuTKIHhuxi8g==,iv:hgZS74nKmudWoodxEo/Fba8n08xd5HpOSWjYfGZ3zYs=,tag:nBRXkB/9/OvWMnMJY35IDQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:EjpkA0FN19KFTy8wF6Ths/dw9ezQYWsIqGuNKl3gqD0gi+vR9CUxUoeQgIVGNZo8O8uYObhS8voIgB39jWw7mft2GIwwwChT,iv:yNf9Sj2XWHkMlhdROAG4fPKC0tJnOFX5CdUjNne3eAg=,tag:WF0XIrfyy8U00dNgxRYn1g==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:jyShOPIa3wJFO8yp0fYA9g6L6pwMJydu7H5/NwxDg3df/dY=,iv:kwralxQfSYhdo1uRAFyW6ltRkwgusjODXODE4a+9azg=,tag:bgEuBR3PsZXcktILt36TwQ==,type:str]
    BASE_URL: ENC[AES256_GCM,data:5j6Lb+o3u/q4ztE7TKVR8TjifEDryKT8rmyvGug=,iv:9zLDvsxAg9hht6aJ8hDIiRSjHaA7WP55a4UVLWof9eg=,tag:4RHgc6jlVkL/LCe8tTmmCQ==,type:str]
    CLIENT_URL: ENC[AES256_GCM,data:jE1cNSQKQs4+gRUqcp5qWSLPduxGViqmELGLad8=,iv:LPDH+Vtf2aT3TclX6YCZGqBg50iF6B3CgpgQc29E6+U=,tag:gMq6h752ITs5257+AztZZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-05T02:06:07Z"
    mac: ENC[AES256_GCM,data:P7Rvmtxqim2Qc8j2MtWgDmDD1nTfd9d0WzhzHuLitop4jUhI3ag8DP2bBws8iTMy5F2usUTRoly8x0Qi0e12q0fIKZ20xgir/7BtJUszg5PIAZzYAFsE+xByMYIp1CcYHeQaNYVCCoVQQaR5z6e2sNn7dRd+nhzpMz7V6FRofpM=,iv:lktdON16LQMnNoXxTWMoJGSI/nC1jt7KUQFl/thmitI=,tag:A+bTumVr3deV05lq1wUAfg==,type:str]
    pgp:
        - created_at: "2025-02-27T03:17:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyR7mfh0bsINAQ/+Ibw6U6TVi/R24RegeNSy6oe7ad4pILrCHZMf6tI7EudE
            ghU6KlGYbkKyB0c9fqV9BS6Q9Aa9GZLmslo5HD0XEX6jAo6IeHC0UiSS0B10Ou8g
            B0XMaxPGthDOuGn3i0OWyiO7xqT/PqnbSq1E1NSEPENOVFVw+RzKyo/z5DP9EYZk
            t9tubnKLTppFBcagZoCEBoI0oYZ51azDTae5P2BBVSy6vEuJ64fxj+YgKDY+2l+M
            wZHBxVI9q1yLhShvjYOCTYS2GYSZ5wSxOdxGxohNfHCE52jqjhdekuBOyehDwwio
            XffCE/w8G+sxL/fZliyd8vTL5U4iEvGS3kptzkL4x/H2/Cv6cu3b3aCCI5wcBJFA
            YU7KRXyTuIGIFhxctDCPOK63ojRgK8NNmBLAtADZ08S426z7HUV2vYLeh/0XsICF
            IowG/eluILJS1PQdoCY7NmbnN4oJni1+MLXCIEmHfM0MUz24XYj4kGbeK38a4SZ7
            /MDH5vPILJrcxrz0z42fZ8RKf/8nX0J7Bb19L/zQGF4UI1hvs+7AQox4OklijbOq
            86bNUhjYZaunlOK8+qL1DtmXr0vlorjx9q4+cuj+wWvmZmT8BcRK63zDp+QDN1uy
            n5ZTIQ+77ODO83Bpp1XGiidyp92xz5HmuYHzLNePvL3qgdvm0pYznVIzXD3ORSjS
            XgHuhx8z+1sN9uL2ZnwcAb35O5h1igP7lAIERlcKvSr57APi063cmRpQbDXj40IG
            LuHPY20C7xBmuQOzNil96ln8ryVpOIik0z9W9sfWO9FITpJJSioOQoQ1pv4qSS4=
            =0a8T
            -----END PGP MESSAGE-----
          fp: C727E1154C6047ED0D0F6F496354D6BDC77CF302
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
