apiVersion: v1
kind: Secret
metadata:
    name: watch-together-secrets
stringData:
    AWS_URL: ENC[AES256_GCM,data:b+k72o3pmzhE+g/4RSW8Te7u0SyE0bs+l182+i4SMQqcSeUkvHZ3vYRiNJWvQ3uHmK/5DrUEbHQ=,iv:hpB7+DpwzrGAnHipPIwjlncK6dqu1cQv84WKoB6wPes=,tag:zSxk0eRRmPQooksZ1g8Xnw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IQUN0Z+E6+rx5iGfw0E+44PoD8o=,iv:/7OdX7C5XDDKSG0NsPf/QmCRcanvCsV5dGnttyNkxQ4=,tag:FM3am6s9xxEcRP6U12Zw5w==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:00decHoF8X/M,iv:mcv9g0j8udEXwW8ciz57R6FA/qPdHRunILZpCyIv9/U=,tag:V2BLklMXsd0Hu9x/EzZsGQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GdlwhWmm6AjlMMv4hLkC+/91y1/cDh5YuCx4rUkETn+UmrFvfjeDqA==,iv:unUCKvvl+I4uFl3GIKG3Q/RvnBJFYuXP2iC0bs00iIY=,tag:LGcx0vRGfUlX5hsEGgAq2g==,type:str]
    AWS_S3_BUCKET: ENC[AES256_GCM,data:6Gvy7vHCz8OiTAbEBO9GDGuTAFQj,iv:SLbrWJA/wVIzYoY45HiO0pn1HZIU2OZhOHMDgPifW54=,tag:nrbonJe6gkTWy64b0lfLeA==,type:str]
    DATABASE_PUBLIC_URL: ENC[AES256_GCM,data:DeZ4dsW3Qn6/w+BoN1arSJI0pabTbVT9/eyvJe6s3ne4lkL8OJ29KqudXanIEk03u+yUDA7+8fZJOXJAQSC8dHYUr/7LqxVSrECoPa6lY1kZHuYto/UEHu6t6HnjSv+cRw==,iv:OjjL5a5nGeMYtR2z+gmFwB9GawuNJkZ2zx1jdnIqnpg=,tag:skUPV2vzRJ2XAHrHY3CAcQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:EjpkA0FN19KFTy8wF6Ths/dw9ezQYWsIqGuNKl3gqD0gi+vR9CUxUoeQgIVGNZo8O8uYObhS8voIgB39jWw7mft2GIwwwChT,iv:yNf9Sj2XWHkMlhdROAG4fPKC0tJnOFX5CdUjNne3eAg=,tag:WF0XIrfyy8U00dNgxRYn1g==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:jyShOPIa3wJFO8yp0fYA9g6L6pwMJydu7H5/NwxDg3df/dY=,iv:kwralxQfSYhdo1uRAFyW6ltRkwgusjODXODE4a+9azg=,tag:bgEuBR3PsZXcktILt36TwQ==,type:str]
    GOOGLE_REDIRECT_URL: ENC[AES256_GCM,data:NV45e1lk/jkmLvRtM4MVh+MLE6vIyN6yC94AKb59yf8IdomdY9UjMew90U7rJS4Mkah1Ph8W0JMqeQ==,iv:SEtHQ7iWz0pb/5kw9LcKq72lhDbo9eehRUzkiexEQHA=,tag:jg0q3oyeEIE/BQnDDaCSNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-27T03:43:06Z"
    mac: ENC[AES256_GCM,data:NKDByFITr4umfbZu/iOyxDXO3VkUkmXeZfnEeqZ8VxG5fD6llYlth19uUwRKKYP4hmAKkNORfUybOjukZZ81KLVhw6qNqhwiy+pmYtLRHdrLV+17PPpqyg07w05BBgS3Ju5uRgGLcRDiBIdkSx/TAv6lJ3HuiOAQn/0/taw+7kg=,iv:iCJuOOPnsapvu2JvUUh4MlRbrPOm2fQCd0UXKN8zsJ4=,tag:0x0lg9t7/RCPCqRRR9TVJQ==,type:str]
    pgp:
        - created_at: "2025-02-27T03:17:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyR7mfh0bsINAQ/+Ibw6U6TVi/R24RegeNSy6oe7ad4pILrCHZMf6tI7EudE
            ghU6KlGYbkKyB0c9fqV9BS6Q9Aa9GZLmslo5HD0XEX6jAo6IeHC0UiSS0B10Ou8g
            B0XMaxPGthDOuGn3i0OWyiO7xqT/PqnbSq1E1NSEPENOVFVw+RzKyo/z5DP9EYZk
            t9tubnKLTppFBcagZoCEBoI0oYZ51azDTae5P2BBVSy6vEuJ64fxj+YgKDY+2l+M
            wZHBxVI9q1yLhShvjYOCTYS2GYSZ5wSxOdxGxohNfHCE52jqjhdekuBOyehDwwio
            XffCE/w8G+sxL/fZliyd8vTL5U4iEvGS3kptzkL4x/H2/Cv6cu3b3aCCI5wcBJFA
            YU7KRXyTuIGIFhxctDCPOK63ojRgK8NNmBLAtADZ08S426z7HUV2vYLeh/0XsICF
            IowG/eluILJS1PQdoCY7NmbnN4oJni1+MLXCIEmHfM0MUz24XYj4kGbeK38a4SZ7
            /MDH5vPILJrcxrz0z42fZ8RKf/8nX0J7Bb19L/zQGF4UI1hvs+7AQox4OklijbOq
            86bNUhjYZaunlOK8+qL1DtmXr0vlorjx9q4+cuj+wWvmZmT8BcRK63zDp+QDN1uy
            n5ZTIQ+77ODO83Bpp1XGiidyp92xz5HmuYHzLNePvL3qgdvm0pYznVIzXD3ORSjS
            XgHuhx8z+1sN9uL2ZnwcAb35O5h1igP7lAIERlcKvSr57APi063cmRpQbDXj40IG
            LuHPY20C7xBmuQOzNil96ln8ryVpOIik0z9W9sfWO9FITpJJSioOQoQ1pv4qSS4=
            =0a8T
            -----END PGP MESSAGE-----
          fp: C727E1154C6047ED0D0F6F496354D6BDC77CF302
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
