---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${email}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          webhook:
            groupName: acme.duckdns.org
            solverName: duckdns
            config:
              apiTokenSecretRef:
                name: duckdns-token-secret
                key: "${domain_token}"
        selector:
          dnsZones:
            - "${domain}"
