apiVersion: v1
kind: Secret
metadata:
    name: duckdns-token-secret
    namespace: cert-manager
stringData:
    domain_token: ENC[AES256_GCM,data:ayoD27Sg+U7Cjg3tlcSiy6ccKF7i+AcjNuclh//ZPQwE5ABJ,iv:W1JRBc1xkTuTxtEMzKFS+f0UDkwCj2ur1WDXuabr6Wc=,tag:9fZvLp83b+3JzMbUPqSo1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-24T07:58:07Z"
    mac: ENC[AES256_GCM,data:Hdxw5dBUKaCqbXlwbn+G4ttM+qrdJs4Oh6Qvpz7BRLkxUvu6UKkwJzGcrFagGBzgRud59PQ8xZgDt4k8jWs5krBZ34LtGssMjutD29i1xdUiYVBQbLwAMXKvJz3EJf3FFzfWLIdIEFvWKYfIy+PqT1nKPBgOTXTzT4ObY/O3xhs=,iv:Rqw6/wwRwWlNBJHxR17JIRBMmoQwfk5AxuYfNdrupL8=,tag:PNdM3liwzgpn7KLcpe5eUQ==,type:str]
    pgp:
        - created_at: "2025-02-24T07:58:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyR7mfh0bsINAQ/+L2PdinfXeo3kwGqWtbi5jrOdrpqvDPqMaXc08q9LvvkE
            OL3r5drKtsunLiwc4U+G4Tb8Luh83YJaBZ2iqd2ZPEy5IbtNAhqTVGmFbKfxqSe/
            lIKNnVj+ljdOpB/3kcK0f1TnbgRGksruwaohBJ6QJSH8b2g3hYn1p6we3hreHjnQ
            5ly0HmKI1le5MC5xGzXVCv+ZZqAIP1LUzkPObHtEBgJ8CLaFYIkXpTL5Zv/oJTTS
            FEPem/vNvuTGw1ea79arKmbO2DNZ/xtQr+jInyFdg0shF7VJM2xtW153r+MlV9nV
            GmEVHzRlAcR42andD60ZEMP+cFHjFl2IbGkY7rH+z0mK6emGZmsB/H0zu8zCQ9OD
            hwiUeHu5DNE6szX9n9kV/lvDoGsj2Z+gktTwm+2A8ttyoFg9M0TSSkvbfGwPKOWF
            JFKWZMSPaFsWFC67+9bqNJY5/klN1kw3uWhrafqYESk9BBMBUzEHMIGaqFuiU9eW
            hZ90THtWALPY9KN/f4InoBHUwbpyk8iMLd0FSc9IcRXYvHx5Ulr1mK/FalPC+f5v
            +OMIhdPshygonHGI7b75oca6Yn/2obgu9dcXV89bOEfXPKvlYMQNlZ70X9v2yAGy
            qlLQI5wxR0cDpkxMl5zJubMZm3Gw7wxt0KxgS/qEO6h+KeqL9kjIV8T1WwMFlEPS
            XAEbJ/58ppfLIXLopm0CF4ZEfBiObXpPfbxyvrBX1DoihUMmc+c8fVxv0njiIzaX
            oMTmmQzaBw6vWugGrdUYO8lOVZrYAlNOCmd4OPqp94OlgJ+YL8sBYMcetEKx
            =kEZg
            -----END PGP MESSAGE-----
          fp: C727E1154C6047ED0D0F6F496354D6BDC77CF302
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
