---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config2
  namespace: utils
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
