---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.0
            env:
              TZ: America/Toronto
              DOTNET_USE_POLLING_FILE_WATCHER: "true"

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        hosts:
          - host: "jellyfin.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main

    service:
      main:
        controller: main
        ports:
          http:
            port: 8096

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /cache/transcodes
            readOnly: false
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /gargantua/
        globalMounts:
          - path: /gargantua
            readOnly: false
