---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: admin
spec:
  interval: 15m
  upgrade:
    force: true
    timeout: 20m
  chart:
    spec:
      chart: postgresql
      version: 16.7.27 # 18.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    global:
      storageClass: "longhorn"
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 17.6.0-debian-12-r4
      digest: ""
      pullPolicy: Always
    primary:
      persistence:
        enabled: true
        size: 10Gi
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
    auth:
      enablePostgresUser: true
      username: "${pg_username}"
      password: "${pg_user_password}"
      postgresPassword: "${pg_password}"
      database: "maindb"
