---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: admin
spec:
  interval: 5m
  timeout: 15m
  upgrade:
    force: true
    cleanupOnFail: true
  rollback:
    timeout: 15m
    recreate: true
    disableHooks: false
  chart:
    spec:
      chart: postgresql
      version: 16.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    global:
      storageClass: "longhorn"
    primary:
      podAnnotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
      persistence:
        enabled: true
        size: 10Gi
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      startupProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 20
      readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 10
    auth:
      enablePostgresUser: true
      username: "${pg_username}"
      password: "${pg_user_password}"
      postgresPassword: "${pg_password}"
      database: "maindb"
